/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.applicationmvc.view;

import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author hesac
 */
public class DichVubaoDuongPanel extends javax.swing.JPanel {

    /**
     * Creates new form DichVubaoDuongPanel
     */
    public DichVubaoDuongPanel() {
        initComponents();
    }
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuong = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton_XacNhanTrongDialogCanhBao = new javax.swing.JButton();
        jDialog_CanhBaoTrungDichVuBaoDuong = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jButton_TatCanhBaoTrungDichVuBD = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField_MaDichVuBaoDuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_PhiDichVuBaoDuong = new javax.swing.JTextField();
        jComboBox_LoaiXe = new javax.swing.JComboBox<>();
        jTextField_TenDichVuBaoDuong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_LuuDichVuBaoDuong = new javax.swing.JButton();
        jCheckBox_TrangThaiSuDungDichVuBaoDuong = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jButton_ThemDichVubaoDUongMoi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_NgayCapNhat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DanhSachDichVuBaoDuong = new javax.swing.JTable();
        jTextField_TimKiemDichVuBaoDuong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuong.setMinimumSize(new java.awt.Dimension(549, 236));
        jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuong.setModal(true);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thay đổi trạng thái của dịch vụ này sẽ ảnh hưởng đến những hóa đơn chưa hoàn thành!!!");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Vui lòng  hoàn thành những hóa đơn trên để thực hiện thay đổi này");

        jButton_XacNhanTrongDialogCanhBao.setText("Tắt");
        jButton_XacNhanTrongDialogCanhBao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XacNhanTrongDialogCanhBaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuongLayout = new javax.swing.GroupLayout(jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuong.getContentPane());
        jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuong.getContentPane().setLayout(jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuongLayout);
        jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuongLayout.setHorizontalGroup(
            jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuongLayout.createSequentialGroup()
                .addGroup(jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuongLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuongLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuongLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jButton_XacNhanTrongDialogCanhBao, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuongLayout.setVerticalGroup(
            jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuongLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton_XacNhanTrongDialogCanhBao)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jDialog_CanhBaoTrungDichVuBaoDuong.setMinimumSize(new java.awt.Dimension(440, 224));
        jDialog_CanhBaoTrungDichVuBaoDuong.setModal(true);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Dịch vụ bảo dưỡng này đã bị trùng!!!");

        jButton_TatCanhBaoTrungDichVuBD.setText("Tắt");
        jButton_TatCanhBaoTrungDichVuBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TatCanhBaoTrungDichVuBDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog_CanhBaoTrungDichVuBaoDuongLayout = new javax.swing.GroupLayout(jDialog_CanhBaoTrungDichVuBaoDuong.getContentPane());
        jDialog_CanhBaoTrungDichVuBaoDuong.getContentPane().setLayout(jDialog_CanhBaoTrungDichVuBaoDuongLayout);
        jDialog_CanhBaoTrungDichVuBaoDuongLayout.setHorizontalGroup(
            jDialog_CanhBaoTrungDichVuBaoDuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_CanhBaoTrungDichVuBaoDuongLayout.createSequentialGroup()
                .addGroup(jDialog_CanhBaoTrungDichVuBaoDuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_CanhBaoTrungDichVuBaoDuongLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel9))
                    .addGroup(jDialog_CanhBaoTrungDichVuBaoDuongLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton_TatCanhBaoTrungDichVuBD, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jDialog_CanhBaoTrungDichVuBaoDuongLayout.setVerticalGroup(
            jDialog_CanhBaoTrungDichVuBaoDuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_CanhBaoTrungDichVuBaoDuongLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jButton_TatCanhBaoTrungDichVuBD)
                .addGap(42, 42, 42))
        );

        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel3.setBackground(new java.awt.Color(248, 164, 136));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Danh sách dịch vụ bảo dưỡng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jTextField_MaDichVuBaoDuong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_MaDichVuBaoDuong.setEditable(false);

        jLabel6.setText("Mã:");

        jTextField_PhiDichVuBaoDuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_PhiDichVuBaoDuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhiDichVuBaoDuongActionPerformed(evt);
            }
        });

        jComboBox_LoaiXe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_TenDichVuBaoDuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_TenDichVuBaoDuong.setAutoscrolls(false);
        jTextField_TenDichVuBaoDuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TenDichVuBaoDuongActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Tên dịch vụ bảo dưỡng:");

        jButton_LuuDichVuBaoDuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_LuuDichVuBaoDuong.setText("Lưu");

        jCheckBox_TrangThaiSuDungDichVuBaoDuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox_TrangThaiSuDungDichVuBaoDuong.setText("Được sử dụng");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Trạng Thái:");

        jButton_ThemDichVubaoDUongMoi.setBackground(new java.awt.Color(204, 204, 255));
        jButton_ThemDichVubaoDUongMoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButton_ThemDichVubaoDUongMoi.setText("Thêm mới ...");
        jButton_ThemDichVubaoDUongMoi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jButton_ThemDichVubaoDUongMoi.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Phí dịch vụ:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Loại xe:");

        jTextField_NgayCapNhat.setEditable(false);

        jLabel10.setText("Ngày cập nhật");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_ThemDichVubaoDUongMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_LuuDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_PhiDichVuBaoDuong)
                    .addComponent(jComboBox_LoaiXe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCheckBox_TrangThaiSuDungDichVuBaoDuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(jTextField_TenDichVuBaoDuong, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_MaDichVuBaoDuong, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_NgayCapNhat, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_MaDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_TenDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PhiDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_LoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_TrangThaiSuDungDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_NgayCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jButton_LuuDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton_ThemDichVubaoDUongMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );

        jPanel2.setBackground(new java.awt.Color(90, 168, 151));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Danh sách các loại xe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jTable_DanhSachDichVuBaoDuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên dịch vụ", "Phí dịch vụ", "Loại xe", "Trạng Thái", "Ngày cập nhật"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_DanhSachDichVuBaoDuong.setRowHeight(30);
        jTable_DanhSachDichVuBaoDuong.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_DanhSachDichVuBaoDuong.setShowGrid(true);
        jTable_DanhSachDichVuBaoDuong.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_DanhSachDichVuBaoDuong);

        jLabel8.setText("Tìm kiếm: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jTextField_TimKiemDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(733, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_TimKiemDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_TenDichVuBaoDuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TenDichVuBaoDuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TenDichVuBaoDuongActionPerformed

    private void jTextField_PhiDichVuBaoDuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhiDichVuBaoDuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhiDichVuBaoDuongActionPerformed

    private void jButton_XacNhanTrongDialogCanhBaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XacNhanTrongDialogCanhBaoActionPerformed
        jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuong.setVisible(false);
    }//GEN-LAST:event_jButton_XacNhanTrongDialogCanhBaoActionPerformed

    private void jButton_TatCanhBaoTrungDichVuBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TatCanhBaoTrungDichVuBDActionPerformed
        jDialog_CanhBaoTrungDichVuBaoDuong.setVisible(false);
    }//GEN-LAST:event_jButton_TatCanhBaoTrungDichVuBDActionPerformed

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JTextField getjTextField_NgayCapNhat() {
        return jTextField_NgayCapNhat;
    }

    public void setjTextField_NgayCapNhat(JTextField jTextField_NgayCapNhat) {
        this.jTextField_NgayCapNhat = jTextField_NgayCapNhat;
    }

    public JButton getjButton_XacNhanTrongDialogCanhBao() {
        return jButton_XacNhanTrongDialogCanhBao;
    }

    public void setjButton_XacNhanTrongDialogCanhBao(JButton jButton_XacNhanTrongDialogCanhBao) {
        this.jButton_XacNhanTrongDialogCanhBao = jButton_XacNhanTrongDialogCanhBao;
    }

    public JDialog getjDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuong() {
        return jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuong;
    }

    public void setjDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuong(JDialog jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuong) {
        this.jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuong = jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuong;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JButton getjButton_TatCanhBaoTrungDichVuBD() {
        return jButton_TatCanhBaoTrungDichVuBD;
    }

    public void setjButton_TatCanhBaoTrungDichVuBD(JButton jButton_TatCanhBaoTrungDichVuBD) {
        this.jButton_TatCanhBaoTrungDichVuBD = jButton_TatCanhBaoTrungDichVuBD;
    }

    public JDialog getjDialog_CanhBaoTrungDichVuBaoDuong() {
        return jDialog_CanhBaoTrungDichVuBaoDuong;
    }

    public void setjDialog_CanhBaoTrungDichVuBaoDuong(JDialog jDialog_CanhBaoTrungDichVuBaoDuong) {
        this.jDialog_CanhBaoTrungDichVuBaoDuong = jDialog_CanhBaoTrungDichVuBaoDuong;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }



    public JButton getjButton_LuuDichVuBaoDuong() {
        return jButton_LuuDichVuBaoDuong;
    }

    public void setjButton_LuuDichVuBaoDuong(JButton jButton_LuuDichVuBaoDuong) {
        this.jButton_LuuDichVuBaoDuong = jButton_LuuDichVuBaoDuong;
    }

    public JLabel getjButton_ThemDichVubaoDUongMoi() {
        return jButton_ThemDichVubaoDUongMoi;
    }

    public void setjButton_ThemDichVubaoDUongMoi(JLabel jButton_ThemDichVubaoDUongMoi) {
        this.jButton_ThemDichVubaoDUongMoi = jButton_ThemDichVubaoDUongMoi;
    }

    public JCheckBox getjCheckBox_TrangThaiSuDungDichVuBaoDuong() {
        return jCheckBox_TrangThaiSuDungDichVuBaoDuong;
    }

    public void setjCheckBox_TrangThaiSuDungDichVuBaoDuong(JCheckBox jCheckBox_TrangThaiSuDungDichVuBaoDuong) {
        this.jCheckBox_TrangThaiSuDungDichVuBaoDuong = jCheckBox_TrangThaiSuDungDichVuBaoDuong;
    }



    public JComboBox<String> getjComboBox_LoaiXe() {
        return jComboBox_LoaiXe;
    }

    public void setjComboBox_LoaiXe(JComboBox<String> jComboBox_LoaiXe) {
        this.jComboBox_LoaiXe = jComboBox_LoaiXe;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }


    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JTextField getjTextField_TimKiemDichVuBaoDuong() {
        return jTextField_TimKiemDichVuBaoDuong;
    }

    public void setjTextField_TimKiemDichVuBaoDuong(JTextField jTextField_TimKiemDichVuBaoDuong) {
        this.jTextField_TimKiemDichVuBaoDuong = jTextField_TimKiemDichVuBaoDuong;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JTextField getjTextField_MaDichVuBaoDuong() {
        return jTextField_MaDichVuBaoDuong;
    }

    public void setjTextField_MaDichVuBaoDuong(JTextField jTextField_MaDichVuBaoDuong) {
        this.jTextField_MaDichVuBaoDuong = jTextField_MaDichVuBaoDuong;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }



    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

 


    public JTable getjTable_DanhSachDichVuBaoDuong() {
        return jTable_DanhSachDichVuBaoDuong;
    }

    public void setjTable_DanhSachDichVuBaoDuong(JTable jTable1) {
        this.jTable_DanhSachDichVuBaoDuong = jTable1;
    }

 

    public JTextField getjTextField1() {
        return jTextField_MaDichVuBaoDuong;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField_MaDichVuBaoDuong = jTextField1;
    }

 
    public JTextField getjTextField_PhiDichVuBaoDuong() {
        return jTextField_PhiDichVuBaoDuong;
    }

    public void setjTextField_PhiDichVuBaoDuong(JTextField jTextField_PhiDichVuBaoDuong) {
        this.jTextField_PhiDichVuBaoDuong = jTextField_PhiDichVuBaoDuong;
    }

    public JTextField getjTextField_TenDichVuBaoDuong() {
        return jTextField_TenDichVuBaoDuong;
    }

    public void setjTextField_TenDichVuBaoDuong(JTextField jTextField_TenDichVuBaoDuong) {
        this.jTextField_TenDichVuBaoDuong = jTextField_TenDichVuBaoDuong;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_LuuDichVuBaoDuong;
    private javax.swing.JButton jButton_TatCanhBaoTrungDichVuBD;
    private javax.swing.JLabel jButton_ThemDichVubaoDUongMoi;
    private javax.swing.JButton jButton_XacNhanTrongDialogCanhBao;
    private javax.swing.JCheckBox jCheckBox_TrangThaiSuDungDichVuBaoDuong;
    private javax.swing.JComboBox<String> jComboBox_LoaiXe;
    private javax.swing.JDialog jDialog_CanhBaoKHiCapNhatTrangThaiCuaDichVuBaoDuong;
    private javax.swing.JDialog jDialog_CanhBaoTrungDichVuBaoDuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_DanhSachDichVuBaoDuong;
    private javax.swing.JTextField jTextField_MaDichVuBaoDuong;
    private javax.swing.JTextField jTextField_NgayCapNhat;
    private javax.swing.JTextField jTextField_PhiDichVuBaoDuong;
    private javax.swing.JTextField jTextField_TenDichVuBaoDuong;
    private javax.swing.JTextField jTextField_TimKiemDichVuBaoDuong;
    // End of variables declaration//GEN-END:variables

}
