/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.applicationmvc.view;

import com.mycompany.applicationmvc.Utils.CustomRenderTable;
import com.mycompany.applicationmvc.Utils.TableColumnUtil;
import com.mycompany.applicationmvc.controller.LinhKienController;
import com.mycompany.applicationmvc.controller.PersonController;

/**
 *
 * @author MinhTo
 */
public class LinhKienPanel extends javax.swing.JPanel {

    /**
     * Creates new form KhachHangPanel
     */
    public LinhKienPanel() {
        initComponents();
       // nhaCungCapTable.getTableHeader().setDefaultRenderer(new CustomRenderTable());
        TableColumnUtil.setTableColumnSize(nhaCungCapTable, nhaCungCapTable.getPreferredSize().getWidth(),5,40,10,45);
        //linhKienTable.getTableHeader().setDefaultRenderer(new CustomRenderTable());
        TableColumnUtil.setTableColumnSize(linhKienTable, linhKienTable.getPreferredSize().getWidth(), 10,40,10,10,10,10);
        LinhKienController controller=new LinhKienController(btnSuaNhaCungCap, btnSuaLinhKien,btnThemLinhKien, btnThemNhaCungCap, btnXoaNhaCungCap, btnXoaLinhKien, errorGia, errorMaLinhKien, errorNgayNhap, errorNhaCungCapComBoBox, errorSoDienThoai, errorSoLuong, errorTenLinhKien, errorTenNhaCC, errorGhiChu, ghiChuTextArea, giaField, lbCMT1, lbGioiTinh2, lbGioiTinh3, lbHoTen1, lbMaKhachHang1, linhKienTable, maLinhKien, maNCC, maNCCField, ngayNhapField, nhaCungCapTable, soDienThoai, soDienThoaiField, soLuongField, tenLinhKienField, tenNCC, tenNCCField, tenNhaCungCapCombobox, timKiemLinhKien, timKiemLinhKienField, timKiemNCC, timKiemNCCField, jPanel1);
        controller.setDataToTable();
        controller.setEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnXoaNhaCungCap = new javax.swing.JButton();
        maNCCField = new javax.swing.JTextField();
        tenNCCField = new javax.swing.JTextField();
        soDienThoaiField = new javax.swing.JTextField();
        maNCC = new javax.swing.JLabel();
        tenNCC = new javax.swing.JLabel();
        soDienThoai = new javax.swing.JLabel();
        ghiChu = new javax.swing.JLabel();
        btnThemNhaCungCap = new javax.swing.JButton();
        btnSuaNhaCungCap = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        nhaCungCapTable = new javax.swing.JTable();
        timKiemNCCField = new javax.swing.JTextField();
        timKiemNCC = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        ghiChuTextArea = new javax.swing.JTextArea();
        errorTenNhaCC = new javax.swing.JLabel();
        errorSoDienThoai = new javax.swing.JLabel();
        errorGhiChu = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        giaField = new javax.swing.JTextField();
        btnXoaLinhKien = new javax.swing.JButton();
        maLinhKien = new javax.swing.JTextField();
        tenLinhKienField = new javax.swing.JTextField();
        soLuongField = new javax.swing.JTextField();
        lbMaKhachHang1 = new javax.swing.JLabel();
        lbHoTen1 = new javax.swing.JLabel();
        lbCMT1 = new javax.swing.JLabel();
        lbGioiTinh2 = new javax.swing.JLabel();
        btnThemLinhKien = new javax.swing.JButton();
        btnSuaLinhKien = new javax.swing.JButton();
        lbGioiTinh3 = new javax.swing.JLabel();
        tenNhaCungCapCombobox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        linhKienTable = new javax.swing.JTable();
        timKiemLinhKien = new javax.swing.JLabel();
        timKiemLinhKienField = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        ngayNhapField = new com.toedter.calendar.JDateChooser();
        errorMaLinhKien = new javax.swing.JLabel();
        errorTenLinhKien = new javax.swing.JLabel();
        errorSoLuong = new javax.swing.JLabel();
        errorGia = new javax.swing.JLabel();
        errorNhaCungCapComBoBox = new javax.swing.JLabel();
        errorNgayNhap = new javax.swing.JLabel();

        setForeground(new java.awt.Color(35, 35, 242));

        jPanel1.setPreferredSize(new java.awt.Dimension(990, 702));
        jPanel1.setRequestFocusEnabled(false);

        jPanel5.setBackground(new java.awt.Color(243, 243, 244));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(0, 0, 153)), "Thông Tin Nhà Cung Cấp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 61))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 500));

        btnXoaNhaCungCap.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnXoaNhaCungCap.setText("Xoá");
        btnXoaNhaCungCap.setPreferredSize(new java.awt.Dimension(70, 35));

        maNCCField.setBackground(new java.awt.Color(243, 243, 244));
        maNCCField.setForeground(new java.awt.Color(102, 102, 102));
        maNCCField.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        maNCCField.setEnabled(false);
        maNCCField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maNCCFieldActionPerformed(evt);
            }
        });

        tenNCCField.setBackground(new java.awt.Color(243, 243, 244));
        tenNCCField.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        soDienThoaiField.setBackground(new java.awt.Color(243, 243, 244));
        soDienThoaiField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        soDienThoaiField.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        soDienThoaiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soDienThoaiFieldActionPerformed(evt);
            }
        });

        maNCC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        maNCC.setText("Mã  nhà cung cấp");

        tenNCC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tenNCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tenNCC.setText("Tên nhà cung cấp");

        soDienThoai.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        soDienThoai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        soDienThoai.setText("Số điện thoại");

        ghiChu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ghiChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ghiChu.setText("Ghi chú");

        btnThemNhaCungCap.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnThemNhaCungCap.setText("Thêm");
        btnThemNhaCungCap.setPreferredSize(new java.awt.Dimension(70, 35));
        btnThemNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhaCungCapActionPerformed(evt);
            }
        });

        btnSuaNhaCungCap.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnSuaNhaCungCap.setText("Lưu");
        btnSuaNhaCungCap.setPreferredSize(new java.awt.Dimension(70, 35));

        nhaCungCapTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã NCC", "Tên", "Số điện điện", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nhaCungCapTable.setShowGrid(true);
        nhaCungCapTable.getTableHeader().setResizingAllowed(false);
        nhaCungCapTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(nhaCungCapTable);

        timKiemNCCField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemNCCFieldActionPerformed(evt);
            }
        });

        timKiemNCC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        timKiemNCC.setText("Tìm kiếm");

        ghiChuTextArea.setColumns(20);
        ghiChuTextArea.setLineWrap(true);
        ghiChuTextArea.setRows(5);
        ghiChuTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(ghiChuTextArea);

        errorTenNhaCC.setIcon(new javax.swing.ImageIcon(LinhKienController.iconImportantURL));
        errorTenNhaCC.setToolTipText("Vui Lòng nhập trường này");

        errorSoDienThoai.setIcon(new javax.swing.ImageIcon(LinhKienController.iconImportantURL));
        errorSoDienThoai.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ghiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tenNCC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(maNCC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tenNCCField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(errorTenNhaCC))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(soDienThoaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(errorSoDienThoai))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(errorGhiChu))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(maNCCField)
                                .addGap(8, 8, 8))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnThemNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnSuaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnXoaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(timKiemNCC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timKiemNCCField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timKiemNCC)
                            .addComponent(timKiemNCCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(maNCCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(maNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(tenNCCField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorTenNhaCC))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(soDienThoaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addComponent(errorSoDienThoai))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(errorGhiChu)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSuaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThemNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXoaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ghiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );

        jPanel6.setBackground(new java.awt.Color(243, 243, 244));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(0, 0, 153)), "Thông Tin Linh Kiện", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 2, 48))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(500, 500));

        giaField.setBackground(new java.awt.Color(243, 243, 244));
        giaField.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        btnXoaLinhKien.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnXoaLinhKien.setText("Xoá");
        btnXoaLinhKien.setPreferredSize(new java.awt.Dimension(70, 35));
        btnXoaLinhKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLinhKienActionPerformed(evt);
            }
        });

        maLinhKien.setEditable(false);
        maLinhKien.setBackground(new java.awt.Color(243, 243, 244));
        maLinhKien.setForeground(new java.awt.Color(153, 153, 153));
        maLinhKien.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        maLinhKien.setEnabled(false);

        tenLinhKienField.setBackground(new java.awt.Color(243, 243, 244));
        tenLinhKienField.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        soLuongField.setBackground(new java.awt.Color(243, 243, 244));
        soLuongField.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        soLuongField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soLuongFieldActionPerformed(evt);
            }
        });

        lbMaKhachHang1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbMaKhachHang1.setText("Mã Linh Kiện");

        lbHoTen1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbHoTen1.setText("Tên linh kiện");

        lbCMT1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbCMT1.setText("Số lượng");

        lbGioiTinh2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbGioiTinh2.setText("Gía");

        btnThemLinhKien.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnThemLinhKien.setText("Thêm");
        btnThemLinhKien.setPreferredSize(new java.awt.Dimension(70, 35));
        btnThemLinhKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLinhKienActionPerformed(evt);
            }
        });

        btnSuaLinhKien.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnSuaLinhKien.setText("Lưu");
        btnSuaLinhKien.setPreferredSize(new java.awt.Dimension(70, 35));

        lbGioiTinh3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbGioiTinh3.setText("Tên nhà cung cấp");

        tenNhaCungCapCombobox.setEditable(true);
        tenNhaCungCapCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        linhKienTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã linh kiện", "Tên", "Số lượng", "Gía", "Mã NCC", "Ngày nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        linhKienTable.setFocusable(false);
        linhKienTable.setShowGrid(true);
        linhKienTable.getTableHeader().setResizingAllowed(false);
        linhKienTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(linhKienTable);

        timKiemLinhKien.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        timKiemLinhKien.setText("Tìm kiếm");

        timKiemLinhKienField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemLinhKienFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Ngày nhập");

        ngayNhapField.setEnabled(false);

        errorMaLinhKien.setToolTipText("Vui Lòng nhập trường này");

        errorTenLinhKien.setToolTipText("Vui Lòng nhập trường này");

        errorSoLuong.setToolTipText("Vui Lòng nhập trường này");

        errorGia.setToolTipText("Vui Lòng nhập trường này");

        errorNhaCungCapComBoBox.setToolTipText("Vui Lòng nhập trường này");

        errorNgayNhap.setToolTipText("Vui Lòng nhập trường này");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbGioiTinh3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbCMT1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbHoTen1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbMaKhachHang1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbGioiTinh2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soLuongField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenNhaCungCapCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngayNhapField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tenLinhKienField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(giaField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorTenLinhKien)
                            .addComponent(errorMaLinhKien)
                            .addComponent(errorGia)
                            .addComponent(errorSoLuong)
                            .addComponent(errorNhaCungCapComBoBox)
                            .addComponent(errorNgayNhap)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnThemLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(timKiemLinhKien)
                        .addGap(12, 12, 12)
                        .addComponent(timKiemLinhKienField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(timKiemLinhKien))
                            .addComponent(timKiemLinhKienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(errorMaLinhKien)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(errorTenLinhKien))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(maLinhKien)
                                            .addComponent(lbMaKhachHang1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                                        .addGap(0, 0, 0)
                                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tenLinhKienField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbHoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(soLuongField)
                                            .addComponent(lbCMT1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)))
                                    .addComponent(errorSoLuong))
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(giaField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbGioiTinh2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(errorGia))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tenNhaCungCapCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbGioiTinh3))
                                    .addComponent(errorNhaCungCapComBoBox))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ngayNhapField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(errorNgayNhap))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSuaLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1138, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1138, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1158, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhaCungCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemNhaCungCapActionPerformed

    private void soDienThoaiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soDienThoaiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soDienThoaiFieldActionPerformed

    private void soLuongFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soLuongFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soLuongFieldActionPerformed

    private void btnThemLinhKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLinhKienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemLinhKienActionPerformed

    private void timKiemNCCFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemNCCFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timKiemNCCFieldActionPerformed

    private void timKiemLinhKienFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemLinhKienFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timKiemLinhKienFieldActionPerformed

    private void maNCCFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maNCCFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maNCCFieldActionPerformed

    private void btnXoaLinhKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLinhKienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaLinhKienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaLinhKien;
    private javax.swing.JButton btnSuaNhaCungCap;
    private javax.swing.JButton btnThemLinhKien;
    private javax.swing.JButton btnThemNhaCungCap;
    private javax.swing.JButton btnXoaLinhKien;
    private javax.swing.JButton btnXoaNhaCungCap;
    private javax.swing.JLabel errorGhiChu;
    private javax.swing.JLabel errorGia;
    private javax.swing.JLabel errorMaLinhKien;
    private javax.swing.JLabel errorNgayNhap;
    private javax.swing.JLabel errorNhaCungCapComBoBox;
    private javax.swing.JLabel errorSoDienThoai;
    private javax.swing.JLabel errorSoLuong;
    private javax.swing.JLabel errorTenLinhKien;
    private javax.swing.JLabel errorTenNhaCC;
    private javax.swing.JLabel ghiChu;
    private javax.swing.JTextArea ghiChuTextArea;
    private javax.swing.JTextField giaField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbCMT1;
    private javax.swing.JLabel lbGioiTinh2;
    private javax.swing.JLabel lbGioiTinh3;
    private javax.swing.JLabel lbHoTen1;
    private javax.swing.JLabel lbMaKhachHang1;
    private javax.swing.JTable linhKienTable;
    private javax.swing.JTextField maLinhKien;
    private javax.swing.JLabel maNCC;
    private javax.swing.JTextField maNCCField;
    private com.toedter.calendar.JDateChooser ngayNhapField;
    private javax.swing.JTable nhaCungCapTable;
    private javax.swing.JLabel soDienThoai;
    private javax.swing.JTextField soDienThoaiField;
    private javax.swing.JTextField soLuongField;
    private javax.swing.JTextField tenLinhKienField;
    private javax.swing.JLabel tenNCC;
    private javax.swing.JTextField tenNCCField;
    private javax.swing.JComboBox<String> tenNhaCungCapCombobox;
    private javax.swing.JLabel timKiemLinhKien;
    private javax.swing.JTextField timKiemLinhKienField;
    private javax.swing.JLabel timKiemNCC;
    private javax.swing.JTextField timKiemNCCField;
    // End of variables declaration//GEN-END:variables
}
