/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.applicationmvc.view;

import com.mycompany.applicationmvc.Bean.DanhMucBean;
import com.mycompany.applicationmvc.Utils.SessionUtil;
import com.mycompany.applicationmvc.controller.SwitchController;
import com.mycompany.applicationmvc.model.TaiKhoanModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author MinhTo
 */
public class MenuFrame extends javax.swing.JFrame {
      public static TaiKhoanModel taiKhoanModel;
    
    
    /**
     * Creates new form ListMenuFrame
     */
    //CONTRUCTOR CÓ 1 THAM SỐ TÀI KHOẢN
    public MenuFrame(TaiKhoanModel taiKhoan) {
        initComponents();
        //setVisible(true);
        List<DanhMucBean> listDanhMuc = new ArrayList<>();
        listDanhMuc.add(new DanhMucBean("trangChinh", null, trangChinhLabel));
        listDanhMuc.add(new DanhMucBean("khachHangPage", null, khachHangLabel));
        listDanhMuc.add(new DanhMucBean("xePage", null, xeLabel));
        listDanhMuc.add(new DanhMucBean("linhKienPage", null, linhKienLabel));
        listDanhMuc.add(new DanhMucBean("donBaoDuongPage", null, donBaoDuongLabel));
        listDanhMuc.add(new DanhMucBean("dichVuBaoDuongPage", null, dichVuBaoDuongLabel));
        listDanhMuc.add(new DanhMucBean("phuTungKiemTraPage", null, phuTungLabel));
        SwitchController c = new SwitchController(this, Panels, listDanhMuc);
        c.setDashBoard(null, khachHangLabel);
        c.setEvent();
        listQuanTri.setVisible(false);//ẩn danh sách quyền quản trị
        taiKhoanModel=taiKhoan;
        if(!taiKhoanModel.getQuyen().equals("Quản Lý"))
            {
                quanTri.setVisible(false);
            }   
        welcomeUserLabel.setText(taiKhoanModel.getTenNhanVien());      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popDown = new javax.swing.JPopupMenu();
        thongtin = new javax.swing.JMenuItem();
        doimatkhau = new javax.swing.JMenuItem();
        dangxuat = new javax.swing.JMenuItem();
        Panels = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        khachHangLabel = new javax.swing.JLabel();
        xeLabel = new javax.swing.JLabel();
        dichVuBD = new javax.swing.JLabel();
        quanTri = new javax.swing.JLabel();
        listQuanTri = new javax.swing.JPanel();
        quyen1 = new javax.swing.JLabel();
        quyen2 = new javax.swing.JLabel();
        quyen3 = new javax.swing.JLabel();
        quyen4 = new javax.swing.JLabel();
        linhKienLabel = new javax.swing.JLabel();
        donBaoDuongLabel = new javax.swing.JLabel();
        welcomeUserLabel = new javax.swing.JLabel();
        trangChinhLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dichVuBaoDuongLabel = new javax.swing.JLabel();
        phuTungLabel = new javax.swing.JLabel();

        thongtin.setText("Thông tin");
        thongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongtinActionPerformed(evt);
            }
        });
        popDown.add(thongtin);

        doimatkhau.setText("Đổi mật khẩu");
        doimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doimatkhauActionPerformed(evt);
            }
        });
        popDown.add(doimatkhau);

        dangxuat.setText("Đăng xuất");
        dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangxuatActionPerformed(evt);
            }
        });
        popDown.add(dangxuat);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panels.setBackground(new java.awt.Color(204, 204, 255));
        Panels.setPreferredSize(new java.awt.Dimension(990, 650));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Quản lí đơn bảo dưỡng");

        javax.swing.GroupLayout PanelsLayout = new javax.swing.GroupLayout(Panels);
        Panels.setLayout(PanelsLayout);
        PanelsLayout.setHorizontalGroup(
            PanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelsLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(384, Short.MAX_VALUE))
        );
        PanelsLayout.setVerticalGroup(
            PanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelsLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPanel.setBackground(new java.awt.Color(243, 243, 244));
        menuPanel.setForeground(new java.awt.Color(0, 0, 61));
        menuPanel.setPreferredSize(new java.awt.Dimension(155, 700));

        khachHangLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        khachHangLabel.setForeground(new java.awt.Color(0, 0, 61));
        khachHangLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        khachHangLabel.setText("Khách Hàng");
        khachHangLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khachHangLabelMouseClicked(evt);
            }
        });

        xeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        xeLabel.setForeground(new java.awt.Color(0, 0, 61));
        xeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xeLabel.setText("Xe");
        xeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xeLabelMouseClicked(evt);
            }
        });

        dichVuBD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dichVuBD.setForeground(new java.awt.Color(0, 0, 61));
        dichVuBD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dichVuBD.setText("Dịch Vụ");

        quanTri.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        quanTri.setForeground(new java.awt.Color(0, 0, 61));
        quanTri.setText("Quản Trị");
        quanTri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quanTriMouseClicked(evt);
            }
        });

        listQuanTri.setBackground(new java.awt.Color(255, 255, 255));
        listQuanTri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listQuanTriMouseClicked(evt);
            }
        });

        quyen1.setBackground(new java.awt.Color(255, 255, 255));
        quyen1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        quyen1.setForeground(new java.awt.Color(0, 0, 61));
        quyen1.setText("quyền 1");

        quyen2.setBackground(new java.awt.Color(255, 255, 255));
        quyen2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        quyen2.setForeground(new java.awt.Color(0, 0, 61));
        quyen2.setText("quyền 2");

        quyen3.setBackground(new java.awt.Color(255, 255, 255));
        quyen3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        quyen3.setForeground(new java.awt.Color(0, 0, 61));
        quyen3.setText("quyền 3");

        quyen4.setBackground(new java.awt.Color(255, 255, 255));
        quyen4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        quyen4.setForeground(new java.awt.Color(0, 0, 61));
        quyen4.setText("quyền 4");

        javax.swing.GroupLayout listQuanTriLayout = new javax.swing.GroupLayout(listQuanTri);
        listQuanTri.setLayout(listQuanTriLayout);
        listQuanTriLayout.setHorizontalGroup(
            listQuanTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listQuanTriLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(listQuanTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quyen4)
                    .addComponent(quyen3)
                    .addComponent(quyen2)
                    .addComponent(quyen1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        listQuanTriLayout.setVerticalGroup(
            listQuanTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listQuanTriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quyen1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quyen2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quyen3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quyen4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        linhKienLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        linhKienLabel.setForeground(new java.awt.Color(0, 0, 61));
        linhKienLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linhKienLabel.setText("Linh Kiện");
        linhKienLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linhKienLabelMouseClicked(evt);
            }
        });

        donBaoDuongLabel.setText("Don bao duong");

        welcomeUserLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        welcomeUserLabel.setForeground(new java.awt.Color(0, 0, 61));
        welcomeUserLabel.setText("Minh Tơ");
        welcomeUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                welcomeUserLabelMouseClicked(evt);
            }
        });

        dichVuBaoDuongLabel.setText("Danh sách dịch vụ bảo dưỡng");

        phuTungLabel.setText("Danh sách phụ tùng kiểm tra");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(linhKienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dichVuBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(xeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(khachHangLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))))
                .addGap(17, 17, 17))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(quanTri, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(listQuanTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(welcomeUserLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(trangChinhLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(phuTungLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(donBaoDuongLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dichVuBaoDuongLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(welcomeUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trangChinhLabel)
                .addGap(18, 18, 18)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(khachHangLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(linhKienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dichVuBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(152, 152, 152)
                .addComponent(quanTri, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listQuanTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(donBaoDuongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dichVuBaoDuongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phuTungLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Panels, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panels, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        Panels.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void khachHangLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHangLabelMouseClicked
//        // TODO add your handling code here:
//        CardLayout cardLayout = (CardLayout) Panels.getLayout();
//        cardLayout.show(Panels, "card2");
    }//GEN-LAST:event_khachHangLabelMouseClicked

    private void xeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xeLabelMouseClicked
        // TODO add your handling code here:
//        CardLayout cardLayout = (CardLayout) Panels.getLayout();
//        cardLayout.show(Panels, "card3");
    }//GEN-LAST:event_xeLabelMouseClicked

    private void listQuanTriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listQuanTriMouseClicked
        // TODO add your handling code here:
        listQuanTri.getRootPane();
    }//GEN-LAST:event_listQuanTriMouseClicked

    private void quanTriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanTriMouseClicked

        if (listQuanTri.isVisible()) {
            listQuanTri.setVisible(false);
        } else {
            listQuanTri.setVisible(true);
        }
    }//GEN-LAST:event_quanTriMouseClicked

    private void linhKienLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linhKienLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_linhKienLabelMouseClicked

    private void welcomeUserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_welcomeUserLabelMouseClicked
        // TODO add your handling code here:
        popDown.show(menuPanel, welcomeUserLabel.getX(), welcomeUserLabel.getY() + welcomeUserLabel.getHeight());
    }//GEN-LAST:event_welcomeUserLabelMouseClicked

    private void thongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongtinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thongtinActionPerformed

    private void doimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doimatkhauActionPerformed
        // TODO add your handling code here
        
        JDialog dialogChangePassword = new ChangePassWordDialog(null, true, taiKhoanModel.getTenTaiKhoan(), taiKhoanModel.getMatKhau());
//        int x = (this.getWidth() / 2) - (dialogChangePassword.getWidth() / 2);
//        int y = (this.getHeight() / 2) - (dialogChangePassword.getHeight() / 2);
        taiKhoanModel=(TaiKhoanModel) SessionUtil.getValue(taiKhoanModel.getTenTaiKhoan());
        welcomeUserLabel.setText(taiKhoanModel.getTenNhanVien()); 
    }//GEN-LAST:event_doimatkhauActionPerformed

    private void dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangxuatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new SigninForm(taiKhoanModel.getTenTaiKhoan()).setVisible(true);
    
    }//GEN-LAST:event_dangxuatActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        </editor-fold>
//        </editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuFrame(null).setVisible(true);
//            }
//        });
//    }

    public JLabel getQuanLiKH() {
        return khachHangLabel;
    }

    public void setQuanLiKH(JLabel quanLiKH) {
        this.khachHangLabel = quanLiKH;
    }

    public JPanel getPanels() {
        return Panels;
    }

    public void setPanels(JPanel Panels) {
        this.Panels = Panels;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panels;
    private javax.swing.JMenuItem dangxuat;
    private javax.swing.JLabel dichVuBD;
    private javax.swing.JLabel dichVuBaoDuongLabel;
    private javax.swing.JMenuItem doimatkhau;
    private javax.swing.JLabel donBaoDuongLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel khachHangLabel;
    private javax.swing.JLabel linhKienLabel;
    private javax.swing.JPanel listQuanTri;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel phuTungLabel;
    private javax.swing.JPopupMenu popDown;
    private javax.swing.JLabel quanTri;
    private javax.swing.JLabel quyen1;
    private javax.swing.JLabel quyen2;
    private javax.swing.JLabel quyen3;
    private javax.swing.JLabel quyen4;
    private javax.swing.JMenuItem thongtin;
    private javax.swing.JLabel trangChinhLabel;
    private javax.swing.JLabel welcomeUserLabel;
    private javax.swing.JLabel xeLabel;
    // End of variables declaration//GEN-END:variables

}
