/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.applicationmvc.view.DonBaoDuong;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author hesac
 */
public class DonBaoDuongContainerPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonBaoDuongContainerPanel
     */
    public DonBaoDuongContainerPanel() {
        initCustom();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public DonBaoDuongPanel getDonBaoDuongPanel() {
        return donBaoDuongPanel;
    }

    public void setDonBaoDuongPanel(DonBaoDuongPanel donBaoDuongPanel) {
        this.donBaoDuongPanel = donBaoDuongPanel;
    }

    public DanhSachDonBaoDuongPanel getDanhSachDonBaoDuongPanel() {
        return danhSachDonBaoDuongPanel;
    }

    public void setDanhSachDonBaoDuongPanel(DanhSachDonBaoDuongPanel danhSachDonBaoDuongPanel) {
        this.danhSachDonBaoDuongPanel = danhSachDonBaoDuongPanel;
    }

    public CardLayout getCard() {
        return card;
    }

    public void setCard(CardLayout card) {
        this.card = card;
    }

    private DonBaoDuongPanel donBaoDuongPanel;
    private DanhSachDonBaoDuongPanel danhSachDonBaoDuongPanel;
    private javax.swing.JPanel container;
    

    private void initCustom() {
        
        container = new JPanel();
        card = new CardLayout();
        container.setLayout(card);
        donBaoDuongPanel  =new DonBaoDuongPanel(card,  container);
        danhSachDonBaoDuongPanel = new DanhSachDonBaoDuongPanel(card,  container);
        container.add(danhSachDonBaoDuongPanel);
        container.add(donBaoDuongPanel);
        card.first(container);
        this.add(container);
        
    }
    
    CardLayout card;
    // Variables declaration - do not modify                     
    // End of variables declaration                   
}

